# thanks to https://devops.tutorials24x7.com/blog/containerize-wordpress-with-nginx-php-mysql-and-phpmyadmin-using-docker-containers
version: "4.26"
services:
  nginx:
    container_name: nginx
    build: ./docker/nginx
    command: nginx -g "daemon off;"
    links:
      - php
    ports:
      - "8080:8080"
    volumes:
      - ./logs/nginx:/var/log/nginx
      - ./src:/var/www/html
  php:
    container_name: php
    build: ./docker/php
    ports:
      - "9000:9000"
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
  mysql:
    image: mysql:8.2.0
    container_name: mysql
    env_file:
      - ./env/mysql.env
    # mysql might refuse connection from docker, to prevent do this steps on new console:
    # docker exec -it mysql mysql -u root -p
    # yes - default root has no password so hit ENTER
    # CREATE USER 'root1'@'%' IDENTIFIED BY 'adminadmin';
    # GRANT ALL PRIVILEGES ON *.* TO 'root1'@'%';
    # CREATE DATABASE mydb;
    # CREATE USER 'mydbu'@'%' IDENTIFIED BY 'mydbpass';
    # GRANT ALL PRIVILEGES ON mydb.* TO 'mydbu'@'%';
    # and at the end
    # FLUSH PRIVILEGES;
    ports:
      - "3306:3306"
    volumes:
      - ./database/mysql:/var/lib/mysql
    command: '--default-authentication-plugin=caching_sha2_password'
  phpmyadmin:
    image: phpmyadmin:5.2.1
    container_name: phpmyadmin
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8085:80